-- Seed data for PANWORLD SCHOOL PARTNER PORTAL (Prisma-free)
-- Includes: publishers, school group + 12 schools, demo users (requested), and basic language preferences.
-- Password hash is bcrypt for: Panworld@123

SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET FOREIGN_KEY_CHECKS = 0;

-- Clear core tables (safe for local demo)
DELETE FROM language_preferences;
DELETE FROM refresh_tokens;
DELETE FROM users;
DELETE FROM schools;
DELETE FROM school_groups;
DELETE FROM publishers;

-- Publishers
INSERT INTO publishers (id, name) VALUES
('pub_mcgraw','McGraw Hill'),
('pub_kodeit','Kodeit Global'),
('pub_studysync','StudySync'),
('pub_achieve','Achieve3000'),
('pub_powerschool','PowerSchool'),
('pub_oxford','Oxford'),
('pub_cambridge','Cambridge'),
('pub_pearson','Pearson/Savvas'),
('pub_collins','Collins'),
('pub_jolly','Jolly Phonics');

-- School group (3 campuses)
INSERT INTO school_groups (id, name) VALUES
('grp_alnoor','Al Noor Education Group');

-- Schools (12)
INSERT INTO schools (id, name, country, curriculum_type, purchase_status, preferred_lang, enabled_modules, branding, vat_rate, group_id) VALUES
('sch_daa','Dubai American Academy','UAE','American','REGISTERED_NO_ORDERS','en',
 JSON_OBJECT('phase1', TRUE, 'phase2', FALSE, 'phase3', FALSE, 'assessment', FALSE, 'kodeitAcademy', TRUE),
 JSON_OBJECT('logoUrl', NULL, 'primaryColor', '#0f172a'), 5.00, NULL),

('sch_adbs','Abu Dhabi British School','UAE','British','FIRST_ORDER_CONFIRMED','en',
 JSON_OBJECT('phase1', TRUE, 'phase2', TRUE, 'phase3', TRUE, 'assessment', FALSE, 'kodeitAcademy', TRUE),
 JSON_OBJECT('logoUrl', NULL, 'primaryColor', '#0f172a'), 5.00, NULL),

('sch_smc','Sharjah Mixed Curriculum School','UAE','Mixed','ACTIVE_REPEAT','en',
 JSON_OBJECT('phase1', TRUE, 'phase2', TRUE, 'phase3', TRUE, 'assessment', FALSE, 'kodeitAcademy', TRUE),
 JSON_OBJECT('logoUrl', NULL, 'primaryColor', '#0f172a'), 5.00, NULL),

('sch_rais','Riyadh American International School','KSA','American','REGISTERED_NO_ORDERS','ar',
 JSON_OBJECT('phase1', TRUE, 'phase2', FALSE, 'phase3', FALSE, 'assessment', TRUE, 'kodeitAcademy', TRUE),
 JSON_OBJECT('logoUrl', NULL, 'primaryColor', '#0f172a'), 15.00, NULL),

('sch_jncc','Jeddah NCC Academy','KSA','Saudi NCC','FIRST_ORDER_CONFIRMED','ar',
 JSON_OBJECT('phase1', TRUE, 'phase2', TRUE, 'phase3', TRUE, 'assessment', TRUE, 'kodeitAcademy', TRUE),
 JSON_OBJECT('logoUrl', NULL, 'primaryColor', '#0f172a'), 15.00, NULL),

('sch_dncs','Dammam National Curriculum School','KSA','Saudi NCC','ACTIVE_REPEAT','ar',
 JSON_OBJECT('phase1', TRUE, 'phase2', TRUE, 'phase3', TRUE, 'assessment', TRUE, 'kodeitAcademy', TRUE),
 JSON_OBJECT('logoUrl', NULL, 'primaryColor', '#0f172a'), 15.00, NULL),

('sch_alnoor_dxb','Al Noor Campus - Dubai','UAE','American','ACTIVE_REPEAT','en',
 JSON_OBJECT('phase1', TRUE, 'phase2', TRUE, 'phase3', TRUE, 'assessment', FALSE, 'kodeitAcademy', TRUE),
 JSON_OBJECT('logoUrl', NULL, 'primaryColor', '#0f172a'), 5.00, 'grp_alnoor'),

('sch_alnoor_auh','Al Noor Campus - Abu Dhabi','UAE','British','ACTIVE_REPEAT','en',
 JSON_OBJECT('phase1', TRUE, 'phase2', TRUE, 'phase3', TRUE, 'assessment', FALSE, 'kodeitAcademy', TRUE),
 JSON_OBJECT('logoUrl', NULL, 'primaryColor', '#0f172a'), 5.00, 'grp_alnoor'),

('sch_alnoor_shj','Al Noor Campus - Sharjah','UAE','IB','FIRST_ORDER_CONFIRMED','en',
 JSON_OBJECT('phase1', TRUE, 'phase2', TRUE, 'phase3', TRUE, 'assessment', FALSE, 'kodeitAcademy', TRUE),
 JSON_OBJECT('logoUrl', NULL, 'primaryColor', '#0f172a'), 5.00, 'grp_alnoor'),

('sch_ajm','Ajman Primary School','UAE','UAE MOE','REGISTERED_NO_ORDERS','en',
 JSON_OBJECT('phase1', TRUE, 'phase2', FALSE, 'phase3', FALSE, 'assessment', FALSE, 'kodeitAcademy', TRUE),
 JSON_OBJECT('logoUrl', NULL, 'primaryColor', '#0f172a'), 5.00, NULL),

('sch_akis','Al Khobar International School','KSA','British','ACTIVE_REPEAT','ar',
 JSON_OBJECT('phase1', TRUE, 'phase2', TRUE, 'phase3', TRUE, 'assessment', TRUE, 'kodeitAcademy', TRUE),
 JSON_OBJECT('logoUrl', NULL, 'primaryColor', '#0f172a'), 15.00, NULL),

('sch_mlc','Madinah Learning Center','KSA','Mixed','REGISTERED_NO_ORDERS','ar',
 JSON_OBJECT('phase1', TRUE, 'phase2', FALSE, 'phase3', FALSE, 'assessment', TRUE, 'kodeitAcademy', TRUE),
 JSON_OBJECT('logoUrl', NULL, 'primaryColor', '#0f172a'), 15.00, NULL);

-- Demo users (requested). Password = Panworld@123
-- bcrypt hash generated by Node bcryptjs (cost 10) for "Panworld@123":
-- $2b$10$c7max.8ruVFJ7I.cFfjmSOrCcEfQHbyAUVDC163vLoXfHJyuBS6Sa
SET @pw_hash = '$2b$10$c7max.8ruVFJ7I.cFfjmSOrCcEfQHbyAUVDC163vLoXfHJyuBS6Sa';

INSERT INTO users (id, email, password_hash, first_name, last_name, role, department, active, preferred_lang, school_id, publisher_id) VALUES
('usr_teacher','teacher@panworld-demo.com',@pw_hash,'Aisha','Teacher','TEACHER','English',1,'en','sch_adbs',NULL),
('usr_hod','hod@panworld-demo.com',@pw_hash,'Omar','HOD','HOD','Math',1,'en','sch_adbs',NULL),
('usr_management','management@panworld-demo.com',@pw_hash,'Sara','Management','MANAGEMENT',NULL,1,'en','sch_adbs',NULL),
('usr_ceo','ceo@panworld-demo.com',@pw_hash,'Khalid','CEO','CEO',NULL,1,'en','sch_adbs',NULL),
('usr_proc','procurement@panworld-demo.com',@pw_hash,'Lina','Procurement','PROCUREMENT',NULL,1,'en','sch_adbs',NULL),
('usr_admin','admin@panworld-demo.com',@pw_hash,'Panworld','Admin','PANWORLD_ADMIN',NULL,1,'en',NULL,NULL),
('usr_sales','sales@panworld-demo.com',@pw_hash,'Layla','Account','SALES_ADMIN',NULL,1,'en',NULL,NULL),
('usr_publisher','publisher@panworld-demo.com',@pw_hash,'Publisher','Partner','PUBLISHER',NULL,1,'en',NULL,'pub_oxford');

-- Language preferences
INSERT INTO language_preferences (id, user_id, lang, rtl) VALUES
('lp_teacher','usr_teacher','en',0),
('lp_hod','usr_hod','en',0),
('lp_management','usr_management','en',0),
('lp_ceo','usr_ceo','en',0),
('lp_proc','usr_proc','en',0),
('lp_admin','usr_admin','en',0),
('lp_sales','usr_sales','en',0),
('lp_publisher','usr_publisher','en',0);

SET FOREIGN_KEY_CHECKS = 1;

